language: node_js
node_js:
  - "stable"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
before_install:
  - cd substitutator
  - npm install istanbul@0
  - pip install --user codecov
script:
  - npm run coverage
after_success:
  - codecov --file coverage/lcov.info --disable search
